- name: Install Tailscale
  include_tasks: setup-{{ ansible_distribution }}.yml

- name: start tailscale service
  service:
      name: tailscaled
      enabled: true
      state: started

- name: check if tailscale is up and connected
  command: grep -i '_daemon' /var/lib/tailscale/tailscaled.state
  register: state
  changed_when: state.failed
  ignore_errors: true

- name: setup Tailscale
  command: "tailscale up --authkey={{ tailscale_key }}"
  when: state.failed

- name: refresh facts for tailscale interface
  setup:
    gather_subset:
      - network
    filter: '*tailscale*'

- name: Set Tailscale IP as host fact
  set_fact:
    tailscale_ip: "{{ ansible_tailscale0.ipv4.address }}"