- name: Install prereq packages
  dnf:
      name: ["epel-release", "dnf-plugins-core"]
      update_cache: yes
      state: present

- name: add Tailscape dnf repo
  command: "dnf config-manager --add-repo https://pkgs.tailscale.com/stable/centos/{{ ansible_distribution_major_version }}/tailscale.repo"
  args:
    creates: /etc/yum.repos.d/tailscale.repo
    warn: false

- name: Install tailscale
  dnf:
      name: tailscale
      update_cache: yes
      state: present