---
- name: Converge
  hosts: all
  vars:
    tailscale_key: "{{ lookup('env', 'TAILSCALE_KEY') }}"
  tasks:
    - name: "Include ansible-tailscale"
      include_role:
        name: "ansible-tailscale"
    - name: "output IP"
      debug:
        msg: "{{ inventory_hostname }}: {{ tailscale_ip }}"
