---
- name: Converge
  hosts: all
  vars:
    tailscale_key: "{{ lookup('env', 'TAILSCALE_KEY') }}"
  tasks:
    - name: Run docker-specific tasks for tailscale
      include_tasks: docker.yml
    - name: "Include ansible-tailscale"
      include_role:
        name: "ansible-tailscale"
      tags: ["check"]
    - name: "output IP"
      debug:
        msg: "{{ inventory_hostname }}: {{ tailscale_ip }}"
