---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: Assert tailscale0 interface is created
    assert:
      that: ansible_tailscale0 is defined