# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"

  pull_request:
    branches: [main]
    paths-ignore:
      - "**/README.md"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.x

      - name: Install lint dependencies
        run: pip3 install yamllint ansible-lint

      - name: Lint role
        run: |
          yamllint .
          ansible-lint .

  molecule:
    name: Molecule test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [centos7, centos8, ubuntu2004, ubuntu1804]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run molecule test
        run: molecule test
        env:
          MOLECULE_DISTRO: ${{matrix.distro}}
          TAILSCALE_KEY: ${{secrets.TAILSCALE_KEY}}
