name: Release

on:
  push:
    tags:
    - '*'
    paths-ignore:
      - 'README.md'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.x

      - name: Install ansible
        run: pip3 install ansible-base

      - name: Publish to Ansible Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
